### ISSUE TITLE
DataInterface with DataSchema

### ISSUE THREAD

**Issue by PeteHart** [RealEstateCore/rec#46] opened 2020-04-19 10:00 UTC
In a similar way as an actuator and its actuation interface can express a payload data schema it'd be beneficial to express a similar reality for data residing in external systems (external to the REC platform implementation).

This requirement has emerged from work with WoT and Thing Descriptions

Proposed solution, preferably for 3.1.1

Introduce a new Software subclass DataInterface
Introduce a new object property hasDataInterface with domain Device and range DataInterface
Introduce a new object property dataSchema with domain DataInterface and range DataSchema
 
Note recommendation to anchor on Device, not Sensor.

**Comment by PeteHart** [comment] 2020-04-20 06:36
After further contemplation, in order not to restrict future modelling in this domain I’d recommend to relax the proposed hasDataInterface to only a range, that’s is an open domain

This implies that everything, for now, can have a DataInterface, makes sense for Observation, Sensor, Device today, and potentially DataSeries and other new classes in 3.2 or later.

**Comment by PeteHart** [comment] 2020-05-02 17:13
#49

**Comment by hammar** [comment] 2020-06-29 07:35
Closed as duplicate of #49, which has been resolved in release 3.2

**Closed by hammar** 2020-06-29 07:35 UTC
Labels: duplicate
